language: python
python:
- 3.6.3
install: pip install -r requirements.txt
services: postgresql
addons: postgresql:"9.6"
before_script:
- export FLASK_APP="run.py"
- export SECRET="$pbkdf2-sha256$29000$I.T8f8/ZG8M4J0QIwTgHIA$.9wCvRZECxd7/yvHttEgoHzpvgjdhjizq5ySewKfeQc"
- export APP_SETTINGS="testing"
- psql -c 'create database Fast-Food-Fast;' -U postgres
script:
- py.test --cov-report term-missing  --cov tests/
after_success: coveralls
deploy:
  provider: heroku
  api_key:
    secure: ZPehm5Yobo0KZK+1POourAziPSXbWktkUOiMLI3T6KY3TDBb7YZqdiWRP8vgi8uNIYFZt80fKx6gk8kfiwIcTN3v/S4eP2jctd1WJDGE/dro7sgep6ggepUB53fjhGefLXggN9Hywdv3WDvw1cfcOqY62G0wZiqEg4dKOlg5v+ydKQk5u7Xxi4gGPrss13n8MsxvEiiO66p0bEcVjMBBZTq0ocQbRmB9epwqrz8B2g3KNzcZdtFIZv8gyLhw6JpEvugLoKyd924VH1ZVtA0BytVs9tkKzrtALE38dplUbIeWo+C5ZxvVVjA833uKPguxSpp+3SHofi+9DJEbl16wwAySmA1xcDEbStnZcoRRQtn8Widvey3fJB7wb6Dh25YrIQLX8qqeOdUYOU+ODz9jtZ/WMqRRk83xoJy0oI0zPh8W/zDyYISni2hd4GXFP1+ynKKk6BO6wntMtOvC7LrAja+3SyDdq0jEdk4MwwwKQ51OQepPD4MCqdbxYNT7GrwjyRbrzYJQXU0aT54EqP9PXDO3f9wSEkulVrZw+bFeGSQPqxxcnOh7Rg8vMnRg2RpzKXaYneQWmisIC8qJDTjbr8gQlg/d43vrhHKAxVOn2Ka9Llcpi4DFVsqQY2PGTAeqKdGlylDkrNmc7jpBnDBq6iBcde9z6Zslhgxri4ouB+U=
