language: python
python:
  - 3.7
install: pip install -r requirements.txt
before_script:
  -export FLASK_APP="run.py"
  -export SECRET="$pbkdf2-sha256$29000$I.T8f8/ZG8M4J0QIwTgHIA$.9wCvRZECxd7/yvHttEgoHzpvgjdhjizq5ySewKfeQc"
  -export APP_SETTINGS="development"