language: python
python:
- 3.6.3
install: pip install -r requirements.txt
services: postgresql
before_script:
- psql -c 'create database fast_food_fast;' -U postgres
- psql -c 'create database test;' -U postgres
- psql -c "select table_name from information_schema.tables where table_schema = 'public';"

script:
- coverage run --source app\V2 -m py.test
- coverage report
after_success: coveralls
deploy:
  provider: heroku
  api_key: 18481de2-d646-41df-96f2-ba23197c3daa
  app: fast-food-really-fast
  on:
    repo: fgkinus/Fast-Food-Fast
    branch: feature/API-V2
